import type { TraceSummary } from '../schema/types'
import type { FilterKeyDef } from './types'

type KeyAccessor = (s: TraceSummary) => string | number | boolean | undefined

interface KeyEntry {
  def: FilterKeyDef
  get: KeyAccessor
}

const ENTRIES: KeyEntry[] = [
  {
    def: {
      id: 'score',
      label: 'Score',
      type: 'number',
      description: 'Grader reward for the trace (higher is better); unset while ungraded',
    },
    get: (s) => s.stats.score ?? undefined,
  },
  {
    def: {
      id: 'status',
      label: 'Status',
      type: 'enum',
      enumSource: 'statuses',
      description: "Trace lifecycle state: 'completed', 'failed' or 'executing'",
    },
    get: (s) => s.meta.status,
  },
  {
    def: {
      id: 'component',
      label: 'Component',
      type: 'enum',
      enumSource: 'components',
      description: "Dataset/component name, e.g. 'swe/swebench-verified-mini'",
    },
    get: (s) => s.meta.component,
  },
  {
    def: {
      id: 'split',
      label: 'Split',
      type: 'enum',
      enumSource: 'splits',
      description: "Dataset split: 'train' or 'test'",
    },
    get: (s) => s.meta.split,
  },
  {
    def: {
      id: 'step',
      label: 'Checkpoint step',
      type: 'number',
      enumSource: 'steps',
      description: 'Training checkpoint step that produced this rollout',
    },
    get: (s) => s.meta.checkpointStep,
  },
  {
    def: {
      id: 'hasError',
      label: 'Has error',
      type: 'boolean',
      description: 'True when a tool call errored or the trace failed',
    },
    get: (s) => s.stats.hasError,
  },
  {
    def: {
      id: 'truncated',
      label: 'Truncated',
      type: 'boolean',
      description: 'True when the trace was cut off by a context or length limit',
    },
    get: (s) => s.stats.truncated,
  },
  {
    def: {
      id: 'turns',
      label: 'Turns',
      type: 'number',
      description: 'Number of assistant steps (contiguous assistant message blocks)',
    },
    get: (s) => s.stats.turns,
  },
  {
    def: {
      id: 'toolUses',
      label: 'Tool uses',
      type: 'number',
      description: 'Total tool calls made by the assistant',
    },
    get: (s) => s.stats.toolUses,
  },
  {
    def: {
      id: 'sandboxExecutions',
      label: 'Sandbox executions',
      type: 'number',
      description: 'Tool results produced by sandbox-class tools (bash, python, run_tests, ...)',
    },
    get: (s) => s.stats.sandboxExecutions,
  },
  {
    def: {
      id: 'totalTokens',
      label: 'Total tokens',
      type: 'number',
      description: 'Input plus output tokens for the whole trace',
    },
    get: (s) => s.stats.totalTokens,
  },
  {
    def: {
      id: 'outputTokens',
      label: 'Output tokens',
      type: 'number',
      description: 'Tokens generated by the assistant',
    },
    get: (s) => s.stats.outputTokens,
  },
  {
    def: {
      id: 'thinkingTokens',
      label: 'Thinking tokens',
      type: 'number',
      description: 'Assistant tokens on the analysis (chain-of-thought) channel',
    },
    get: (s) => s.stats.thinkingTokens,
  },
  {
    def: {
      id: 'thinkingPortion',
      label: 'Thinking portion',
      type: 'number',
      description: 'thinkingTokens / outputTokens, in [0, 1]',
    },
    get: (s) => s.stats.thinkingPortion,
  },
  {
    def: {
      id: 'durationMs',
      label: 'Duration (ms)',
      type: 'number',
      description: 'Wall-clock duration in milliseconds; unset when timing is unknown',
    },
    get: (s) => s.stats.durationMs,
  },
  {
    def: {
      id: 'instanceId',
      label: 'Instance ID',
      type: 'string',
      description: 'Task identity, stable for the same instance across checkpoints',
    },
    get: (s) => s.meta.instanceId,
  },
  {
    def: {
      id: 'traceId',
      label: 'Trace ID',
      type: 'string',
      description: 'Unique identifier of the trace',
    },
    get: (s) => s.meta.traceId,
  },
  {
    def: {
      id: 'sourceFormat',
      label: 'Source format',
      type: 'string',
      description: "Connector that produced the trace: 'native', 'harmony', 'openai-chat', ...",
    },
    get: (s) => s.meta.sourceFormat,
  },
  {
    def: {
      id: 'model',
      label: 'Model',
      type: 'string',
      description: 'Name of the model that generated the trace',
    },
    get: (s) => s.stats.model?.name,
  },
]

export const FILTER_KEYS: FilterKeyDef[] = ENTRIES.map((e) => e.def)

export const FILTER_KEY_MAP: ReadonlyMap<string, FilterKeyDef> = new Map(
  ENTRIES.map((e) => [e.def.id, e.def]),
)

const ACCESSORS: ReadonlyMap<string, KeyAccessor> = new Map(ENTRIES.map((e) => [e.def.id, e.get]))

export function getKeyValue(
  summary: TraceSummary,
  keyId: string,
): string | number | boolean | undefined {
  return ACCESSORS.get(keyId)?.(summary)
}
