import { recordedCheckpoint } from '../schema/provenance'
import type { TraceSummary } from '../schema/types'
import type { FilterKeyDef } from './types'

type KeyAccessor = (s: TraceSummary) => string | number | boolean | undefined

interface KeyEntry {
  def: FilterKeyDef
  get: KeyAccessor
}

/** Typed reads over the untyped meta.extra bag; wrong-typed or missing values ⇒ undefined. */
function extraOf(s: TraceSummary, key: string): unknown {
  return s.meta.extra?.[key]
}

function extraNumber(s: TraceSummary, key: string): number | undefined {
  const v = extraOf(s, key)
  return typeof v === 'number' && Number.isFinite(v) ? v : undefined
}

function extraBoolean(s: TraceSummary, key: string): boolean | undefined {
  const v = extraOf(s, key)
  return typeof v === 'boolean' ? v : undefined
}

function extraString(s: TraceSummary, key: string): string | undefined {
  const v = extraOf(s, key)
  return typeof v === 'string' ? v : undefined
}

const ENTRIES: KeyEntry[] = [
  {
    def: {
      id: 'score',
      label: 'Score',
      type: 'number',
      description: 'Grader reward for the trace (higher is better); unset while ungraded',
    },
    get: (s) => s.stats.score ?? undefined,
  },
  {
    def: {
      id: 'status',
      label: 'Status',
      type: 'enum',
      enumSource: 'statuses',
      description: "Trace lifecycle state: 'completed', 'failed', 'executing' or 'unknown'",
    },
    get: (s) => s.meta.status,
  },
  {
    def: {
      id: 'component',
      label: 'Component',
      type: 'enum',
      enumSource: 'components',
      description: "Dataset/component name, e.g. 'swe/swebench-verified-mini'",
    },
    get: (s) => s.meta.component,
  },
  {
    def: {
      id: 'split',
      label: 'Split',
      type: 'enum',
      enumSource: 'splits',
      description: "Dataset split: 'train', 'test' or 'unknown'",
    },
    get: (s) => s.meta.split,
  },
  {
    def: {
      id: 'step',
      label: 'Checkpoint step',
      type: 'number',
      enumSource: 'steps',
      description: 'Training checkpoint step that produced this rollout',
    },
    get: (s) => recordedCheckpoint(s.meta) ?? undefined,
  },
  {
    def: {
      id: 'hasError',
      label: 'Has error',
      type: 'boolean',
      description: 'True when a tool call errored or the trace failed',
    },
    get: (s) => s.stats.hasError,
  },
  {
    def: {
      id: 'truncated',
      label: 'Truncated',
      type: 'boolean',
      description: 'True when the trace was cut off by a context or length limit',
    },
    get: (s) => s.stats.truncated,
  },
  {
    def: {
      id: 'turns',
      label: 'Turns',
      type: 'number',
      description: 'Number of assistant steps (contiguous assistant message blocks)',
    },
    get: (s) => s.stats.turns,
  },
  {
    def: {
      id: 'toolUses',
      label: 'Tool uses',
      type: 'number',
      description: 'Total tool calls made by the assistant',
    },
    get: (s) => s.stats.toolUses,
  },
  {
    def: {
      id: 'sandboxExecutions',
      label: 'Sandbox executions',
      type: 'number',
      description: 'Tool results produced by sandbox-class tools (bash, python, run_tests, ...)',
    },
    get: (s) => s.stats.sandboxExecutions,
  },
  {
    def: {
      id: 'totalTokens',
      label: 'Total tokens',
      type: 'number',
      description: 'Input plus output tokens for the whole trace',
    },
    get: (s) => s.stats.totalTokens,
  },
  {
    def: {
      id: 'outputTokens',
      label: 'Output tokens',
      type: 'number',
      description: 'Tokens generated by the assistant',
    },
    get: (s) => s.stats.outputTokens,
  },
  {
    def: {
      id: 'thinkingTokens',
      label: 'Thinking tokens',
      type: 'number',
      description: 'Assistant tokens on the analysis (chain-of-thought) channel',
    },
    get: (s) => s.stats.thinkingTokens,
  },
  {
    def: {
      id: 'thinkingPortion',
      label: 'Thinking portion',
      type: 'number',
      description: 'thinkingTokens / outputTokens, in [0, 1]',
    },
    get: (s) => s.stats.thinkingPortion,
  },
  {
    def: {
      id: 'durationMs',
      label: 'Duration (ms)',
      type: 'number',
      description: 'Wall-clock duration in milliseconds; unset when timing is unknown',
    },
    get: (s) => s.stats.durationMs,
  },
  {
    def: {
      id: 'instanceId',
      label: 'Instance ID',
      type: 'string',
      description: 'Task identity, stable for the same instance across checkpoints',
    },
    get: (s) => s.meta.instanceId,
  },
  {
    def: {
      id: 'traceId',
      label: 'Trace ID',
      type: 'string',
      description: 'Unique identifier of the trace',
    },
    get: (s) => s.meta.traceId,
  },
  {
    def: {
      id: 'sourceFormat',
      label: 'Source format',
      type: 'string',
      description: "Connector that produced the trace: 'native', 'harmony', 'openai-chat', ...",
    },
    get: (s) => s.meta.sourceFormat,
  },
  {
    def: {
      id: 'model',
      label: 'Model',
      type: 'string',
      description: 'Name of the model that generated the trace',
    },
    get: (s) => s.stats.model?.name,
  },
  {
    def: {
      id: 'kl',
      label: 'KL divergence',
      type: 'number',
      description:
        'KL divergence of the policy from the reference model for this rollout; unset when the trainer did not report it',
    },
    get: (s) => extraNumber(s, 'kl'),
  },
  {
    def: {
      id: 'trainerBatch',
      label: 'Trainer batch',
      type: 'number',
      description: 'Trainer batch index that produced this rollout; unset when unknown',
    },
    get: (s) => extraNumber(s, 'trainer_batch'),
  },
  {
    def: {
      id: 'contextUtil',
      label: 'Context utilization',
      type: 'number',
      description:
        "Total tokens divided by the model's context window, in [0, 1]; 0 when the context window is unknown",
    },
    get: (s) => {
      const util = s.stats.totalTokens / (s.stats.model?.contextWindow ?? Infinity)
      return Math.round(util * 10_000) / 10_000
    },
  },
  {
    def: {
      id: 'zeroLogprobSpan',
      label: 'Zero-logprob span',
      type: 'boolean',
      description:
        'True when the trace contains a suspicious run of tokens with logprob exactly 0 (possible training anomaly)',
    },
    get: (s) => extraBoolean(s, 'zero_logprob_span'),
  },
  {
    def: {
      id: 'formatErrors',
      label: 'Format errors',
      type: 'boolean',
      description:
        'True when any assistant tool call had malformed (unparseable) arguments in this trace',
    },
    get: (s) => {
      const count = extraNumber(s, 'format_errors')
      return count === undefined ? undefined : count > 0
    },
  },
  {
    def: {
      id: 'endReason',
      label: 'End reason',
      type: 'string',
      description:
        "Why the rollout ended, e.g. 'solved', 'gave_up', 'context_limit', 'tool_failure'; unset when unknown",
    },
    get: (s) => extraString(s, 'end_reason'),
  },
  // Owned by Track v1.2 (cross-run comparison) — keep as the LAST entry.
  {
    def: {
      id: 'run',
      label: 'Run',
      type: 'string',
      description: "Training run name (meta.extra.run), e.g. 'run-a'; absent ⇒ 'run-a'",
    },
    get: (s) => (typeof s.meta.extra?.run === 'string' ? s.meta.extra.run : 'run-a'),
  },
]

export const FILTER_KEYS: FilterKeyDef[] = ENTRIES.map((e) => e.def)

export const FILTER_KEY_MAP: ReadonlyMap<string, FilterKeyDef> = new Map(
  ENTRIES.map((e) => [e.def.id, e.def]),
)

const ACCESSORS: ReadonlyMap<string, KeyAccessor> = new Map(ENTRIES.map((e) => [e.def.id, e.get]))

export function getKeyValue(
  summary: TraceSummary,
  keyId: string,
): string | number | boolean | undefined {
  return ACCESSORS.get(keyId)?.(summary)
}
