import { chromium } from 'playwright'
const browser = await chromium.launch()
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
await page.goto('http://localhost:5173/trace/swebench-i01-s275-r01', { waitUntil: 'networkidle' })
const input = page.locator('[data-testid="trace-search"]')
await input.fill('django')
await page.waitForTimeout(600)
console.log('count:', await page.locator('[data-testid="search-count"]').textContent())
const scrollOf = () => page.evaluate(() => Math.max(...[document.scrollingElement, ...document.querySelectorAll('*')].filter(e => e && e.scrollHeight > e.clientHeight + 50).map(e => e.scrollTop), 0))
const s1 = await scrollOf()
await input.press('Enter')
await page.waitForTimeout(600)
const s2 = await scrollOf()
console.log('scroll after first Enter:', s1, '->', s2)
console.log('count now:', await page.locator('[data-testid="search-count"]').textContent())
await browser.close()
